[package]
name = "hack_asm"
version = "0.1.0"
edition = "2021"

[features]
trace=[]
measure=[]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev_dependencies]
assert_cmd = "2"
predicates = "2"